apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pr08as5f2-python
  janus-idp.io/tekton: pr08as5f2-python
  backstage.io/kubernetes-id: pr08as5f2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pr08as5f2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
